### ISSUE TITLE
Bunch of SMS

### ISSUE THREAD

**Issue by VeeraAndroid** [EverythingMe/easy-content-providers#2]
Hi, 
1. 1. How to show **repeat same number** sms are in listview (bunch of sms)?
2. 2. How to **Search sms** (like **Offer** sms, **Friends** sms )?
Thanks.

**Comment by sromku** [comment]
@VeeraAndroid 
You can get SMS as `Cursor` or as `List`. Check this options: https://github.com/EverythingMe/easy-content-providers/wiki/Android-providers#prefer-collection-or-cursor. If you want to populate ListView you can use [CursorAdapter](http://developer.android.com/reference/android/widget/CursorAdapter.html).

For searching over sms, you will need to implement it yourself. This library gives you all SMSes and the only filtering options are by **inbox, outbox, draft, sent or all**.

**Comment by sromku** [comment]
@VeeraAndroid if you have more issues, please let me know
