### ISSUE TITLE
Could not find me.everything:providers-android:1.0.1.

### ISSUE THREAD

**Issue by gerardoeg** [EverythingMe/easy-content-providers#25]
I found this issue since I think now jcenter is not available anymore, I fixed it by adding the maven repository in the project's gradle file.

```
  allprojects {
  
      repositories {
  
          // other maven repositories
  
          maven {
  
              // https://mvnrepository.com/artifact/me.everything/providers-android/1.0.1
              url 'https://repo.spring.io/plugins-release/'
          }

        // ...
    }
}
```

**Comment by Mkurbanov** [comment]
not working for me

**Comment by mwdle** [comment]
Doesn't work for me either, this is the error I see:
Could not GET 'https://repo.spring.io/plugins-release/me/everything/providers-android/1.0.1/providers-android-1.0.1.pom'. Received status code 401 from server: 
It looks like this plugin has been removed or made private on the spring repositories.

Maybe it's hosted somewhere else? I haven't been able to get this working as of yet.

**Comment by mwdle** [comment]
After some more research and experimenting I got it working using Jitpack [https://jitpack.io/#EverythingMe/easy-content-providers/b81beb8532](https://jitpack.io/#EverythingMe/easy-content-providers/b81beb8532).

In project build.gradle:
```
allprojects {
    repositories {
        google()
        maven { url 'https://jitpack.io' }
        mavenCentral()
    }
}
```

In module build.gradle dependencies:
`implementation 'com.github.EverythingMe.easy-content-providers:providers-android:b81beb8532'`
