### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by hay12396** [EverythingMe/easy-content-providers#8]
Hello,

I am receiving NoSuchFieldError exception when trying to use 
`calendarProvider.getCalendars();` method if i'm using Proguard.

What rules do we need to add to the proguard-rules.pro in order to avoid this issue?

*Note that when Proguard is off everything works as it should.

With regards,
Hay.

**Comment by hay12396** [comment]
For anyone lookin for it, adding this fixed the issue:

`-keep class me.everything.providers.core.** { *; }`

**Comment by gerardoepitacio** [comment]
Suggested rule didn't work, tried with this one for R8.

`-keep class me.everything.** { *; }`
